### ISSUE TITLE
[Feat] 토큰 expand 구현

### ISSUE THREAD

**Issue by Arkingco** [Arkingco/42_minishell#10]
### ISSUE
 * Type: `feature`
 * Detail: 토큰 expand구현하기
 
 ### TODO
- [x]  토큰을 순회해서 해당하는 토믄 타입이 word인지 확인하다
- [x]  토큰 타입이 word라면 해당하는 토큰에 확장 $가 있는지 확인한다
     - 토큰 타입은 총 WORD, SINGLE_QOUTE, DOUBLE_QOUTE가 있다 체크는 더블 쿼트 .워드 만하는걸로하자!
- [x]  확장 문구인 $가 있다면 $ 옆에 있는 문자를 확인하여 확장해야하는 값의 키를 가져온다.
     - 확장 키로 올 수 있는 값은 영어 소문자, 대문자, 숫자, 언더바 말고 없다고 한다 이 외에 다른 조건이 오면 무조건 틀림
- [x] 키 값을 가져오고 타입에 따라서 확장해준다.
     - 123$a'123'$b"123" 이라는 str로 들어 온다면
     - strjoin을 사용해여 확장 앞과 뒤를 붙히자
     - 123 + ($a = ls -l) + "123" + ($b = cat - e)
     - 123ls -l'123'cat -e"123"
         - 123ls
         - -l'123'cat
         - -e"123"
         - 이런식으로 토큰화?? 
     - 전부다 치환하고 ifs단위로 끊어줘서 WORD토큰으로 받아주자!!

**Comment by brixxt27** [comment]
키 값을 가져오고 확장할 때 어떤 문제가 있나요?

**Comment by Arkingco** [comment]
확장을 할 때 어떤 방식으로 확장을 할껀지가 문제라고 생각 됩니다.. 앞뒤로 str_join써서 붙이고 워드 단위로 토크나이징 하고 등등등 아몰랑

**Comment by Arkingco** [comment]
대충 구조를 짜봤는데 혹시 문제 있어보이면 말슴해주세요!
