### ISSUE TITLE
[feat] tokenize string to token

### ISSUE THREAD

**Issue by CodyKat** [Arkingco/42_minishell#11]
### ISSUE
 * feat : 우리가 읽은 라인을 토큰단위로 쪼개는 기능을 구현하는 작업
 
 ### TODO
- [x]  word, pipe, redirect 의 구조체를 구성
- [x]  라인을 읽어서 토큰 단위로 구분

**Comment by Arkingco** [comment]
Assignees 달아주세요!!!

**Comment by CodyKat** [comment]
토큰 단위로 나누기 성공! 추후 $확장과 token join에 대한 이슈 생성예정
