### ISSUE TITLE
[comment] file_path 가 아닌 exec_path 로 수정 요망

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_minishell#13]
https://github.com/Arkingco/42_minishell/blob/ba7791ce14d5f47d0c63a044122829102883b513/kipark_jayoon_minishell/grammer.md?plain=1#L11

**Comment by Arkingco** [comment]
내용 확인 하였습니다
이 부분은 자윤님 브랜치에서 수정 하셔도 좋을 것 같습니다!!

**Comment by brixxt27** [comment]
수정 완료
