### ISSUE TITLE
[feat] 기본적으로 모두 T_WORD 라 T_NULL 이 없어도 되지 않나요?

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_minishell#14]
https://github.com/Arkingco/42_minishell/blob/ba7791ce14d5f47d0c63a044122829102883b513/kipark_jayoon_minishell/includes/parse.h#L39

**Comment by Arkingco** [comment]
코드리뷰 없이 진행되어서 전달이 안되었네요 주의하겠습니다!!
T_NULL 을 사용한 이유는 토큰의 끝을 알기 위해서 넣었습니다. 
이 방식 말고도 토큰의 마지막을 알 수 있는 방식은 많겠지만 제일 직관적인 것 같아 추가 하였습니다
