### ISSUE TITLE
[feat] tokens to cmd_struct. 토큰들을 실행부에서 전달받을 구조체로 저장

### ISSUE THREAD

**Issue by CodyKat** [Arkingco/42_minishell#16]
### ISSUE
* feat
 
 ### TODO
- [x]  실행부로 넘겨줄 구조체를 정의
- [x]  토큰들을 구조체에 저장하여 반환

**Comment by CodyKat** [comment]
아 assigned 까먹었네

**Comment by Arkingco** [comment]
ㅋㅋㅋ 어싸인해줭~

**Comment by CodyKat** [comment]
token 들을 cmd_struct 연결리스트에 저장하여 반환성공
