### ISSUE TITLE
[fix] 레포 메인 리드미 날라감 복구작업

### ISSUE THREAD

**Issue by Arkingco** [Arkingco/42_minishell#19]
### ISSUE
 * Type: `fix`
 * Detail: 메인 리드미 날라간 상황 발생!? 복구해주세요!!! 잼전!!
 
 ### TODO
- [x]  리드미 복구 완료

**Comment by CodyKat** [comment]
저런..제가 한번 해보겠습니다! 왠지 제가 날려버렸던것 같음
