### ISSUE TITLE
code convention 정하기

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_minishell#20]
### 개요
같이 작업함에 따라 convention 통일이 코드 가독성에 도움이 될 것 같아 의견 냅니다.
다음과 같은 형식으로 진행해볼까 하는데 의견 있는 사람 댓글 남겨주세요!

### 형식
- 함수명: 명령문 or 의문문(동사로 시작)
- 변수: 명사(단, flag 변수 등 특별한 경우에는 함수명과 같은 조건 가능)
- 헤더파일 명: 명사
- 구조체 명: 명사

**Comment by CodyKat** [comment]
코딩 표준이 있는건 좋은것 같아요! [가능한한.. 함수는 명확한 목적을 가진 단 한개의 역할만을 한다.] 제안 합니당!
