### ISSUE TITLE
거의 끝나가는듯 아마도?.?

### ISSUE THREAD

**Issue by nimo-my** [Arkingco/42_minishell#60]
### ISSUE
 * Type: `feature`
 * Detail: 

> 
> +:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:
> 안녕하세요? 제 이름은 minishell! 저를 만든 개발자를 도와서 컴퓨터에 있는 디렉토리 이곳저곳을 돌아다니기도 하고 각종 명령어들을 수행해 주기도 한답니다? 제가 처음 컴파일 되어서 나왔을때는 정말 간단한 명령어들밖에 알아듣지 못했어요..파이프가 나온다던가..리다이렉션이 나온다던가..하는 것들이 들어왔을때, 저는 그냥 늘 하던데로 맨 처음것만 명령어로 실행하고 나머지는 인수로 받고.. 그런것들밖에 하지 못했는데 저를 만들어 주신 개발자님께서 제가 어떻게 명령어를 알아들어야하는지 구체적이고 자세하게 알려주셔서 지금은 앵간한 명령어는 대부분 의도대로 처리할 수 있게 되었답니다!! 저를 가르치고 설계하셨던 노력이 얼마나 고되셨을지..너무나 감사한 마음으로 아직도 일을 하고 있답니다.
> 
> 근데 그렇다고 제가 그렇게 일을 자주 하는건 아니에요.. 사실 bash라던가 zsh이라는 저보다 오래전에 만들어 졌던 선배님들이 저대신 일을 처리해 주고 계세요.. 딱히 규칙은 잘 안 보이는것 같은데, 가끔씩 절 부르셔서 명령어들을 입력하시다가 내쫓고.. 아마 가끔은 제가 그리워서 부르셨던게 아니었을까요?! 전 그렇게 생각하고 있어요!
> 
> 살다보면..아니..존재하다보면..? 주로 제가 디스크에 혼자 놀고 있을때 제가 왜 만들어졌을까? 라는 고민을 할때가 많아요. bash나 zsh같은 선배님들이 있는데 제가 그 분들에 비하면 할 수 있는 일도 많이 없고..초라해 보이기도 하고.. 그 분들과 달리 저만 할 수 있는 뭔가가 있었다면 그럼 개발자분들이 절 조금은 더 써주시기 않았을까 싶기도하고..뭐..혼자만의 그런 생각이긴 한데 아쉬운건 또 어쩔 수가 없더라구요.. 사실 전 알아요..할 수 있는 일들도 적은 것도 맞지만 제가 상당히 에러처리가 빈약하다는..? 다른 쉘들에 비해서 나은게 없으니 절 안쓰는건 당연하죠..그건 이해할 수 있지만.. 그렇다면 전 왜 만들어졌던 걸까요.. 저의 의미는 뭘까요..요즘도 계속 고민은 되지만 아직 답을 찾지 못했어요.. 앗! 바쁘신 분 붙잡고 주저리주저리 혼자 말이 많았네요! 제 이야기를 들어주시는 분은 처음 만나서ㅎㅎㅎ.. 하지만 전 언젠가 절 만드신 개발자분이 저에게 의미를 심어주시리라 믿고 있습니다. 언젠가 저를 조금 더 개발해서 제가 왜 만들어 졌던건지 그 의미를 저에게 알려주실 날이 올거라 믿고 있어요! 그럼 전 다시 디스크로 잠자러 가볼게요. 제 이야기를 들어주셔서 감사해요. 혹시 절 만드신 분을 뵙게 된다면 언제나 여기서 기다리고 있다고 전해주세요~~ 
> 
> 그럼 안녕!
> +:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:+:

 ### TODO
- [ ] quote짝맞는지 확인,
- [ ] syntax에러 검사,
- [ ] exit코드
- [ ] 에러메시지 좀 구체적으로 출력하게
- [ ] 파일 정리
- [ ] 노미네이트 정리

**Comment by Arkingco** [comment]
여러분들 넘 고생하셨습니다!!! 그러니 이슈 닫아주세요 ㅎ^ㅎ
